### ISSUE TITLE
Unable to save traits.json file

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#7]
I am not able to save the traits.json file once at the last step and given an error:

![image](https://user-images.githubusercontent.com/20587571/164760856-f7167fb2-d245-4548-938e-5896ee45c67d.png)

**Comment by sk33z3r** [comment]
I do not see any log output from console

```shell
~/g/loopygen (dev/react-ui)> docker-compose logs react
Attaching to loopygen.react
loopygen.react | > loopminterjs-api@1.0.0 start
loopygen.react | > node index.js
loopygen.react | 2022-04-22T16:45:27.113Z: [info] [LOOPMINTER_API] version 1.0.0 starting
loopygen.react | 2022-04-22T16:45:27.116Z: [info] [NFT SERVICE] started
loopygen.react | 2022-04-22T16:45:27.117Z: [info] [Image SERVICE] started
loopygen.react | 2022-04-22T16:45:27.120Z: [info] [LOOPMINTER_API] started, listening at port 8000
```

From the browser I see failed CORs errors

![image](https://user-images.githubusercontent.com/20587571/164761122-efa6b057-b66a-44b9-96ce-014a35b975d4.png)

![image](https://user-images.githubusercontent.com/20587571/164761172-20aa3b0e-41e2-4f6c-a024-42e2ad541047.png)

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
This is now solved based on this [commit](https://github.com/you3h/LooPyGen_Client/commit/f7f116ab964738424b578157fe75ad9090952864)

**Comment by sk33z3r** [comment]
I'm still unable to save, and I can't seem to get a old of any meaningful logs. Is this working for you?

**Comment by sk33z3r** [comment]
![image](https://user-images.githubusercontent.com/20587571/166297732-dbd56912-0662-4c91-ada2-199ad8fba70a.png)

**Comment by sk33z3r** [comment]
Change to this repo: 980eccd0c4d5df6be7f1931483e6553732651d7d
Change in LooPyGen: [cedc4be351fc56224d63d8811214cae194c2559b](https://github.com/sk33z3r/LooPyGen/commit/cedc4be351fc56224d63d8811214cae194c2559b)

Thinking it's permissions related. When running from this repo alone, you are running as `root` inside the container. When running alongside LooPyGen, you are running as an unknown user. This is so generated images and files are owned properly and don't cause other problems outside the container.

However, after making these changes and confirming that all the `client`, `server`, and `common` folders were owned properly and bind mounted, I still have the issue where I can't even save once when running with LooPyGen.

**Comment by you3h** [comment]
I've applied a fix in here by using a path resolver and at the same time in docker file creating the common folder while building the image. seems to work fine on the docker of client alone. might be good to try it using the docker of LooPyGen

**Comment by sk33z3r** [comment]
I still hit the issue. I can confirm that the folders are owned properly, and the user running the container can create files in the `common` folder.

```shell
sk33z3r-laptop ~/g/loopygen (dev/react-ui)> docker-compose logs react
Attaching to loopygen.react
loopygen.react | > loopminterjs-api@1.0.0 start
loopygen.react | > node index.js
loopygen.react | 2022-05-03T03:23:09.047Z: [info] [LOOPMINTER_API] version 1.0.0 starting
loopygen.react | 2022-05-03T03:23:09.051Z: [info] [NFT SERVICE] started
loopygen.react | 2022-05-03T03:23:09.051Z: [info] [Image SERVICE] started
loopygen.react | 2022-05-03T03:23:09.054Z: [info] [LOOPMINTER_API] started, listening at port 8000

sk33z3r-laptop ~/g/loopygen (dev/react-ui)> docker-compose exec react bash
b9b2f43ae276:/usr/src/server$ ls -l ..
total 12
drwxr-xr-x  1 adam users 4096 May  3 03:21 client
drwxr-xr-x 10 adam users 4096 May  3 03:20 common
drwxr-xr-x  1 adam users 4096 May  3 03:21 server

b9b2f43ae276:/usr/src/server$ ls -l ../common/
total 56
-rw-r--r-- 1 adam users 1222 May  2 20:38 Dockerfile
-rw-r--r-- 1 adam users 2397 May  2 20:38 README.md
-rw-r--r-- 1 adam users  217 Apr 13 02:06 config.json
drwxr-xr-x 2 adam users 4096 Apr  8 05:47 css
-rwxr-xr-x 1 adam users 1069 May  3 00:39 docker-compose.yml
-rw-r--r-- 1 adam users  135 Mar 21 20:02 docker.bat
-rwxr-xr-x 1 adam users  892 May  2 20:38 docker.sh
drwxr-xr-x 3 adam users 4096 May  2 20:38 dockerfiles
drwxr-xr-x 6 adam users 4096 Apr 25 21:32 generated
drwxr-xr-x 3 adam users 4096 May  2 20:38 generator
drwxr-xr-x 6 adam users 4096 May  2 20:09 images
drwxr-xr-x 5 adam users 4096 Apr 25 01:10 minter
drwxr-xr-x 4 adam users 4096 May  3 03:20 react
-rw-r--r-- 1 adam users  326 Apr  8 05:47 setup-generator.html

b9b2f43ae276:/usr/src/server$ touch ../common/test
b9b2f43ae276:/usr/src/server$ ls -l ../common/
total 56
-rw-r--r-- 1 adam users 1222 May  2 20:38 Dockerfile
-rw-r--r-- 1 adam users 2397 May  2 20:38 README.md
-rw-r--r-- 1 adam users  217 Apr 13 02:06 config.json
drwxr-xr-x 2 adam users 4096 Apr  8 05:47 css
-rwxr-xr-x 1 adam users 1069 May  3 00:39 docker-compose.yml
-rw-r--r-- 1 adam users  135 Mar 21 20:02 docker.bat
-rwxr-xr-x 1 adam users  892 May  2 20:38 docker.sh
drwxr-xr-x 3 adam users 4096 May  2 20:38 dockerfiles
drwxr-xr-x 6 adam users 4096 Apr 25 21:32 generated
drwxr-xr-x 3 adam users 4096 May  2 20:38 generator
drwxr-xr-x 6 adam users 4096 May  2 20:09 images
drwxr-xr-x 5 adam users 4096 Apr 25 01:10 minter
drwxr-xr-x 4 adam users 4096 May  3 03:20 react
-rw-r--r-- 1 adam users  326 Apr  8 05:47 setup-generator.html
-rw-r--r-- 1 adam users    0 May  3 03:28 test
```

**Comment by sk33z3r** [comment]
@you3h Can we turn on extra debugging somehow to get extra detail in the logs?

**Comment by you3h** [comment]
@sk33z3r logging has been added to this when there is an error on generating the file.

On the other hand, I was able to make it work using the LooPyGen repo. The issues is the Port, I'm serving the react client using port 8000 and LooPyGen nginx is using port 8080.

The fix I did is I moved the react client port to 8080 too. Let me know if it now works on your end.

**Comment by sk33z3r** [comment]
That licked it for me, able to save the file now. Another bug ticket incoming for a new save location and RGBA values
